import { ArrowUpRight, Github, Linkedin, Mail, Download, Database, Cloud, GitBranch, BarChart3, Server, Brain, Layers3, Workflow, Code2 } from "lucide-react";

const projects = [
  { title:"Hospital Patient Flow Analytics", type:"DATA ENGINEERING · BI", text:"A synthetic healthcare analytics project demonstrating medallion architecture, SQL data engineering, data quality management, dimensional modelling and business-focused insights.", tags:["SQL","SQL Server","Databricks","Lakeflow","Power BI"], href:"https://github.com/Michaela-de-Bruyn/hospital-patient-flow-analytics", tone:"rose", icon:BarChart3 },
  { title:"Patient Readmission Prediction", type:"MACHINE LEARNING", text:"A machine learning project exploring whether patient demographic, clinical and admission-related data can predict 30-day readmission, covering EDA, feature engineering, model comparison and evaluation.", tags:["Python","Pandas","EDA","Feature Engineering","Scikit-Learn"], href:"https://github.com/Michaela-de-Bruyn/patient-readmission-model", tone:"lav", icon:Brain },
  { title:"Urban Basket Data Engineering", type:"DATA ENGINEERING", text:"An end-to-end data engineering project using a fictional retail dataset. Covers SQL Server, data quality validation, dimensional modelling, Star Schema, Medallion Architecture and ETL design.", tags:["SQL Server","SQL","ETL / ELT","Star Schema","Medallion"], href:"https://github.com/Michaela-de-Bruyn/urban-basket-data-engineering", tone:"pink", icon:Database },
  { title:"Incubeta Data Engineer Assessment", type:"DATA ENGINEERING", text:"A practical data engineering assessment project demonstrating data preparation, transformation and engineering problem-solving in a real-world style workflow.", tags:["SQL","Data Engineering","ETL","Data Transformation"], href:"https://github.com/Michaela-de-Bruyn/incubeta-data-engineer-assessment", tone:"lilac", icon:Workflow }
];
const upcoming = [
  { title:"Data Migration Pipeline", text:"Building an end-to-end migration solution with source extraction, incremental loads, watermarks, control tables, validation, reconciliation and error handling.", tags:["Incremental Loads","Watermarks","Control Tables","Data Quality"] },
  { title:"Modern Data Platform", text:"Building a practical platform spanning Data Warehouse, Data Mart and Data Lakehouse concepts, with layered architecture, dimensional modelling and analytics-ready datasets.", tags:["Data Warehouse","Data Mart","Lakehouse","Data Modelling"] }
];
const skills = [["SQL",Database],["Python",Code2],["Databricks",Layers3],["AWS Cloud",Cloud],["GCP",Cloud],["SQL Server",Server],["Power BI",BarChart3],["Git & GitHub",GitBranch],["ETL / ELT",Database],["Data Modelling",Layers3],["Data Validation",Server],["Machine Learning",Brain]] as const;
const journey = [
 { date:"Jul 2026 — Present", role:"Junior Data Engineer", org:"BrightLearn · Project-Based Data Engineering Programme", text:"Building an end-to-end e-commerce data platform using SQL Server, Databricks and Python. Developing pipelines, dimensional models, validation and analytical datasets." },
 { date:"Sep 2025 — Jun 2026", role:"Scrum Master", org:"Momentum", text:"Led Agile delivery across data-focused teams, established delivery processes, built reporting and analysed Jira delivery data for continuous improvement." },
 { date:"Dec 2023 — Aug 2025", role:"Scrum Master / Analyst", org:"Metropolitan", text:"Combined Agile delivery with reporting automation, SQL/data analysis and Power BI dashboards across multiple delivery teams." },
 { date:"Sep 2023 — Dec 2023", role:"Business Analyst", org:"Pragma · Project-Based Engagement", text:"Documented business systems and processes, facilitated stakeholder workshops and translated requirements into actionable development work." },
 { date:"Jul 2022 — Aug 2023", role:"BI Analyst", org:"Pep", text:"Developed Looker Studio dashboards, performed SQL analysis and supported data migration, validation and data dictionary work during a cloud transition." },
 { date:"Feb 2018 — Nov 2021", role:"Data Analyst → Technical / Data Projects", org:"Mixx Co. · Project-Based", text:"Built a foundation in SQL, Power BI and analytics before moving into cloud migration, ingestion, testing, validation and ETL concepts." }
];

export default function Home(){return <main>
<nav className="nav"><div className="container nav-inner"><a className="logo serif" href="#">M<span>.</span></a><div className="nav-links"><a href="#about">About</a><a href="#work">Work</a><a href="#skills">Skills</a><a href="#experience">Journey</a><a href="#contact">Contact</a></div><a className="nav-cta" href="#contact">Let's connect ↗</a></div></nav>
<section className="hero"><div className="hero-wash"/><div className="container hero-grid"><div className="hero-copy reveal"><div className="eyebrow">DATA ENGINEER · DATA ANALYST</div><h1>Building data<br/>systems <em>with<br/>purpose.</em></h1><p>I build reliable data pipelines, transform complex datasets, and turn data into systems that support better decisions.</p><div className="actions"><a className="button dark" href="#work">View my work <ArrowUpRight size={16}/></a><a className="button light" href="/michaela-de-bruyn-cv.pdf" target="_blank">Download CV <Download size={15}/></a></div><div className="socials"><a href="https://github.com/Michaela-de-Bruyn" target="_blank"><Github size={18}/> GitHub</a><a href="https://www.linkedin.com/in/michaela-de-bruyn/" target="_blank"><Linkedin size={18}/> LinkedIn</a><a href="mailto:michaelardb@gmail.com"><Mail size={18}/> Email</a></div></div><div className="portrait-wrap reveal delay-1"><div className="portrait-frame"><img src="/michaela-headshot.jpeg" alt="Professional portrait of Michaela de Bruyn"/></div><div className="portrait-note float"><span>✦</span><div><b>Data · Technology · Growth</b><small>Turning complexity into clarity.</small></div></div></div></div></section>
<section id="about" className="about about-first"><div className="container about-grid"><div className="about-heading"><div className="eyebrow">01 — ABOUT ME</div><h2>My career path?<br/><em>More like a scenic route.</em></h2><div className="about-route"><span>IT</span><i>→</i><span>DATA</span><i>→</i><span>ENGINEERING</span></div></div><div className="about-copy"><p>Apparently, my career forgot to follow a straight line. On paper, it might look a little unexpected: <strong>IT → Data Analysis → BI → Business Analysis → Scrum Master → Data Engineering.</strong> But when I look at it as a whole, every role added another piece to the puzzle.</p><p>I’ve built technical skills, worked with data, understood business problems, supported teams and processes, worked with stakeholders and spent a lot of time sitting between the technical and business sides of technology. Over time, I realised I wanted to move closer to the technical side again — to understand what happens behind the scenes and build the systems that make data useful.</p><p>That’s what led me to Data Engineering. The deeper I go into <strong>SQL, databases, ETL, data pipelines, data modelling and cloud platforms</strong>, the more curious I become about how all the pieces fit together. I’m naturally curious, eager to learn and usually the person asking, “Okay… but how does this actually work?”</p><p>I also see my mix of technical and non-technical experience as an advantage. I understand the data and technology, but I also understand business problems, communication and the people who need the solution. I enjoy <strong>bridging that gap</strong> — translating business needs into technical thinking and making technical concepts easier to understand.</p><p>So, no — I’m not starting over. <strong>I’m building on everything I’ve already learned and adding a new technical layer.</strong> Right now, my focus is becoming a strong Data Engineer, getting hands-on, continuing to learn and seeing where my curiosity takes me next. Apparently, the scenic route can still get you where you’re going.</p><div className="about-note"><span>THE SHORT VERSION</span><b>Technical enough to build. Business-minded enough to understand the why. Curious enough to keep asking how.</b></div></div></div></section>
<section id="work" className="section"><div className="container"><div className="section-head"><div><div className="eyebrow">02 — SELECTED WORK</div><h2>Things I’ve built.</h2></div><a className="view-all" href="https://github.com/Michaela-de-Bruyn" target="_blank">View GitHub <ArrowUpRight size={15}/></a></div><div className="project-grid">{projects.map((p,i)=>{const Icon=p.icon;return <a className="project reveal" style={{animationDelay:`${i*80}ms`}} href={p.href} target="_blank" key={p.title}><div className={`project-art ${p.tone}`}><span><Icon/></span><small>{p.type}</small></div><h3>{p.title}</h3><p>{p.text}</p><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div><div className="project-link">View project on GitHub <ArrowUpRight size={15}/></div></a>})}</div></div></section>
<section className="upcoming"><div className="container"><div className="eyebrow">03 — WHAT’S NEXT</div><div className="upcoming-head"><h2>Currently building<br/><em>what comes next.</em></h2><p>My portfolio is evolving alongside my Data Engineering journey — with the next projects focused on reliable movement of data and modern analytical architecture.</p></div><div className="upcoming-grid">{upcoming.map((p,i)=><article className="up-card reveal" key={p.title}><div className="status"><span className="pulse"/> IN PROGRESS / UPCOMING</div><div className="up-number">0{i+1}</div><h3>{p.title}</h3><p>{p.text}</p><div className="tags">{p.tags.map(t=><span key={t}>{t}</span>)}</div></article>)}</div></div></section>
<section id="skills" className="toolbox"><div className="container"><div className="eyebrow">04 — TECHNICAL TOOLBOX</div><div className="toolbox-inner"><div className="toolbox-title"><h2>Technologies <em>I work with.</em></h2><p>Strong analytics foundations, now moving deeper into data engineering and cloud.</p></div><div className="skill-grid">{skills.map(([name,Icon])=><div className="skill" key={name}><Icon/><b>{name}</b></div>)}</div></div></div></section>
<section id="experience" className="journey-section"><div className="container"><div className="eyebrow">05 — MY CAREER JOURNEY</div><div className="journey-intro"><div><h2>Different turns.<br/><em>Same destination.</em></h2><p>A career built across technical, analytical and business-facing roles — now coming together in Data Engineering.</p></div><div className="journey-summary"><span>THE ROUTE</span><b>IT → DATA ANALYSIS → BI → BUSINESS ANALYSIS → SCRUM / DELIVERY → DATA ENGINEERING</b><small>Every chapter added another piece to the puzzle.</small></div></div><div className="roadmap">{journey.map((x,i)=><article className="road-item reveal" key={x.date+x.role}><div className="road-node"><span>{String(i+1).padStart(2,"0")}</span></div><div className="road-content"><div className="road-top"><span className="road-date">{x.date}</span><span className="road-stage">{i===0?"CURRENT":i===journey.length-1?"FOUNDATION":"CHAPTER"}</span></div><h3>{x.role}</h3><div className="company">{x.org}</div><p>{x.text}</p></div></article>)}</div></div></section>
<section className="recognition"><div className="container recognition-inner"><div><div className="eyebrow">06 — RECOGNITION</div><h2>Recognised for making an impact in <em>tech.</em></h2></div><div className="award-card"><div className="award-mark">TOP 10</div><div><div className="award-kicker">TELKOM · 2023</div><h3>Telkom Top 10 Phenomenal Women in Tech Award</h3><p>Recognised among Telkom’s Phenomenal 10 for contributions to the technology industry — a recognition of innovation, impact and growth within tech.</p><a href="https://www.linkedin.com/feed/update/urn:li:activity:7102578023530455041/" target="_blank">View recognition <ArrowUpRight size={15}/></a></div></div></div></section>
<section className="next"><div className="container next-inner"><div><div className="eyebrow">07 — NEXT CHAPTER</div><h2>Cloud is<br/><em>calling. ☁️</em></h2></div><div className="next-copy"><p>I’m continuing to upskill in AWS Cloud and build stronger cloud foundations alongside Data Engineering. The goal is simple: understand not only how to build data solutions, but how they fit into modern cloud environments.</p><div className="mini-track"><span>DATA ENGINEERING</span><i>→</i><span>AWS CLOUD</span><i>→</i><span>KEEP BUILDING</span></div></div></div></section>
<section id="contact" className="contact"><div className="container contact-inner"><div><div className="eyebrow">08 — GET IN TOUCH</div><h2>Let’s build something<br/><em>meaningful.</em></h2><p>Open to Data Engineering, Data Analytics and interesting data projects.</p></div><a className="contact-button" href="mailto:michaelardb@gmail.com">Start a conversation <ArrowUpRight size={16}/></a></div></section>
<footer><div className="container footer-inner"><span>© 2026 Michaela de Bruyn</span><span className="mono">BUILT WITH PURPOSE · ONE DATASET AT A TIME ✦</span></div></footer>
</main>}
